# Generated by Django 3.0.4 on 2020-04-02 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Event Status',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveIntegerField()),
                ('channel', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=512)),
                ('images', models.URLField()),
                ('subscription_fee', models.PositiveIntegerField()),
                ('no_of_tickets', models.PositiveIntegerField()),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Promotion')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.EventStatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.EventType')),
            ],
            options={
                'unique_together': {('name', 'type', 'date', 'time')},
            },
        ),
    ]
