# Generated by Django 3.0.4 on 2020-04-08 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200407_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
