# Generated by Django 3.0.4 on 2020-04-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200403_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.CharField(max_length=512),
        ),
    ]
