# Generated by Django 3.0.4 on 2020-04-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200408_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_links',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
