# Generated by Django 3.0.4 on 2020-04-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200404_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sold_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
