# Generated by Django 3.0.4 on 2020-04-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
    ]
