# Generated by Django 3.0.4 on 2020-04-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200408_1933'),
        ('core', '0008_auto_20200410_1044'),
    ]

    operations = [
    ]
