# Generated by Django 3.0.4 on 2020-04-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200413_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.CharField(default='events/default.jpeg', max_length=512),
        ),
    ]
