# Generated by Django 3.0.4 on 2020-04-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200414_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventPreference',
        ),
    ]
