# Generated by Django 3.0.4 on 2020-04-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_feedback_question_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='answer',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
