# Generated by Django 3.0.4 on 2020-04-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200422_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment',
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='id_payment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
