# Generated by Django 3.0.4 on 2020-04-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date Range Filter')),
                ('type', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date Range Filter')),
                ('amount', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'SUCCESSFUL'), (1, 'FAILED'), (2, 'IN_PROGRESS'), (3, 'DECLINED')])),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.PaymentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
