# Generated by Django 3.0.4 on 2020-04-07 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date Range Filter')),
                ('amount', models.PositiveIntegerField()),
                ('discount_amount', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('ref_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'SUCCESSFUL'), (1, 'FAILED'), (2, 'IN_PROGRESS'), (3, 'DECLINED')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
