# Generated by Django 3.0.4 on 2020-04-06 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='discount',
            new_name='discount_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.CharField(default='INVOICE', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='ref_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'SUCCESSFUL'), (1, 'FAILED'), (2, 'IN_PROGRESS'), (3, 'DECLINED')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CASH'), (1, 'CARD')]),
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
