# Generated by Django 3.0.4 on 2020-04-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200407_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CREDIT'), (3, 'REFUND')], default=0),
        ),
    ]
