# Generated by Django 3.0.4 on 2020-04-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
    ]
