# Generated by Django 3.0.4 on 2020-04-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200402_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.Status'),
        ),
    ]
