# Generated by Django 3.0.4 on 2020-04-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_role_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_active',
        ),
    ]
