# Generated by Django 3.0.4 on 2020-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_role_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date Range Filter')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'verification_code',
                'verbose_name_plural': 'verification_codes',
                'db_table': 'verification_code',
                'managed': True,
            },
        ),
    ]
