# Generated by Django 3.0.4 on 2020-04-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=15),
        ),
    ]
