# Generated by Django 3.0.4 on 2020-04-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200406_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='role',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.Role'),
        ),
    ]
