# Generated by Django 3.0.4 on 2020-04-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200406_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
